services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USERNAME: user
        ENV: prod
    container_name: udco2s-to-sqlite-py
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "3"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - db-volume:/home/user/workspace/db
    environment:
      DEVICE_PORT: "/dev/ttyACM0"
      DB_PATH: "./db/udco2s_data.db"
      TABLE_NAME: "sensor_data"
      INTERVAL_SEC: "10"

volumes:
  db-volume:
